import type {
  CallReportCard,
  CallReportRow,
  CallTranscriptLine,
  ReportChannelData,
  ReportTabKey,
  ReportsMockData,
} from "../../types/reports.types";
import EyePng from "../../assets/icons/eye.png";
import MouseCircleGreenIcon from "../../assets/icons/mouse-circle-green.svg";
import ProfileTwoUserIcon from "../../assets/icons/profile-2user.svg";
import MouseCircleIcon from "../../assets/icons/mouse-circle.svg";
import DollarCircleIcon from "../../assets/icons/dollar-circle.svg";

const getCards = (baseSpend: number): ReportChannelData["cards"] => [
  { id: "impressions", label: "Total Impressions", value: "5412" },
  { id: "clicks", label: "Total Clicks", value: "4912" },
  { id: "conversions", label: "Conversions", value: "202" },
  { id: "spent", label: "Total Spend", value: `$${baseSpend.toFixed(2)}` },
  { id: "ctr", label: "CTR (Click-Through Rate)", value: "4%" },
  { id: "convRate", label: "Conversion Rate", value: "6.7%" },
  { id: "cpc", label: "CPC (Cost per Click)", value: "$12" },
  { id: "cpa", label: "CPA (Cost per Lead)", value: "$40" },
];

const getRows = (channelName: string): ReportChannelData["rows"] => [
  {
    id: `${channelName}-1`,
    campaignName: `${channelName} IVF Awareness – December`,
    totalImpressions: 105,
    totalClicks: 82,
    conversions: 36,
    totalSpend: "$10.50",
    ctr: "14.8%",
    conversionRate: "41.2%",
    cpc: "$10.50",
    cpa: "$10.50",
  },
  {
    id: `${channelName}-2`,
    campaignName: `${channelName} Search – Fertility Treatments`,
    totalImpressions: 120,
    totalClicks: 91,
    conversions: 42,
    totalSpend: "$11.75",
    ctr: "21.0%",
    conversionRate: "48.7%",
    cpc: "$11.75",
    cpa: "$11.75",
  },
  {
    id: `${channelName}-3`,
    campaignName: `Warm Leads Follow-up – ${channelName}`,
    totalImpressions: 135,
    totalClicks: 85,
    conversions: 29,
    totalSpend: "$12.25",
    ctr: "23.5%",
    conversionRate: "55.3%",
    cpc: "$12.25",
    cpa: "$12.25",
  },
  {
    id: `${channelName}-4`,
    campaignName: `${channelName} – Fertility Enquiry`,
    totalImpressions: 110,
    totalClicks: 94,
    conversions: 33,
    totalSpend: "$13.00",
    ctr: "19.7%",
    conversionRate: "39.8%",
    cpc: "$13.00",
    cpa: "$13.00",
  },
  {
    id: `${channelName}-5`,
    campaignName: `${channelName} – Dr. Alex Carrey`,
    totalImpressions: 125,
    totalClicks: 88,
    conversions: 27,
    totalSpend: "$14.50",
    ctr: "20.0%",
    conversionRate: "62.0%",
    cpc: "$14.50",
    cpa: "$14.50",
  },
  {
    id: `${channelName}-6`,
    campaignName: `${channelName} IVF Awareness – December`,
    totalImpressions: 102,
    totalClicks: 97,
    conversions: 45,
    totalSpend: "$10.99",
    ctr: "15.3%",
    conversionRate: "37.4%",
    cpc: "$10.99",
    cpa: "$10.99",
  },
  {
    id: `${channelName}-7`,
    campaignName: `${channelName} – Fertility Treatments`,
    totalImpressions: 145,
    totalClicks: 81,
    conversions: 38,
    totalSpend: "$12.80",
    ctr: "18.2%",
    conversionRate: "44.1%",
    cpc: "$12.80",
    cpa: "$12.80",
  },
  {
    id: `${channelName}-8`,
    campaignName: `${channelName} – Fertility Enquiry`,
    totalImpressions: 130,
    totalClicks: 90,
    conversions: 40,
    totalSpend: "$14.10",
    ctr: "16.9%",
    conversionRate: "49.9%",
    cpc: "$14.10",
    cpa: "$14.10",
  },
  {
    id: `${channelName}-9`,
    campaignName: `${channelName} – Dr. Alex Carrey`,
    totalImpressions: 115,
    totalClicks: 83,
    conversions: 25,
    totalSpend: "$11.20",
    ctr: "24.0%",
    conversionRate: "66.3%",
    cpc: "$11.20",
    cpa: "$11.20",
  },
  {
    id: `${channelName}-10`,
    campaignName: `${channelName} IVF Awareness – December`,
    totalImpressions: 140,
    totalClicks: 96,
    conversions: 50,
    totalSpend: "$15.00",
    ctr: "12.5%",
    conversionRate: "36.5%",
    cpc: "$15.00",
    cpa: "$15.00",
  },
  {
    id: `${channelName}-11`,
    campaignName: `${channelName} IVF Awareness – January`,
    totalImpressions: 118,
    totalClicks: 86,
    conversions: 31,
    totalSpend: "$12.40",
    ctr: "17.2%",
    conversionRate: "45.6%",
    cpc: "$12.40",
    cpa: "$12.40",
  },
  {
    id: `${channelName}-12`,
    campaignName: `${channelName} Search – IVF Packages`,
    totalImpressions: 126,
    totalClicks: 95,
    conversions: 44,
    totalSpend: "$13.25",
    ctr: "20.6%",
    conversionRate: "52.4%",
    cpc: "$13.25",
    cpa: "$13.25",
  },
  {
    id: `${channelName}-13`,
    campaignName: `${channelName} Warm Leads Retargeting`,
    totalImpressions: 132,
    totalClicks: 84,
    conversions: 30,
    totalSpend: "$11.95",
    ctr: "18.8%",
    conversionRate: "43.1%",
    cpc: "$11.95",
    cpa: "$11.95",
  },
  {
    id: `${channelName}-14`,
    campaignName: `${channelName} IVF Follow-up Campaign`,
    totalImpressions: 149,
    totalClicks: 98,
    conversions: 47,
    totalSpend: "$14.85",
    ctr: "22.4%",
    conversionRate: "58.0%",
    cpc: "$14.85",
    cpa: "$14.85",
  },
  {
    id: `${channelName}-15`,
    campaignName: `${channelName} Doctor Awareness Push`,
    totalImpressions: 121,
    totalClicks: 87,
    conversions: 35,
    totalSpend: "$12.10",
    ctr: "19.1%",
    conversionRate: "47.2%",
    cpc: "$12.10",
    cpa: "$12.10",
  },
];

const buildChannel = (name: string, spend: number): ReportChannelData => ({
  cards: getCards(spend),
  rows: getRows(name),
});

export const REPORTS_MOCK_DATA: ReportsMockData = {
  facebook: buildChannel("Facebook", 341.21),
  gmail: buildChannel("Gmail", 288.45),
  instagram: buildChannel("Instagram", 301.36),
  "google-ads": buildChannel("Google Ads", 410.08),
  linkedin: buildChannel("LinkedIn", 256.14),
  email: buildChannel("Email", 221.33),
  call: buildChannel("Call", 189.2),
};

export const REPORTS_TABS: { key: ReportTabKey; label: string }[] = [
  { key: "facebook", label: "Facebook" },
  { key: "gmail", label: "Gmail" },
  { key: "instagram", label: "Instagram" },
  { key: "google-ads", label: "Google Ads" },
  { key: "linkedin", label: "LinkedIn" },
  { key: "email", label: "Email" },
  { key: "call", label: "Call" },
];

export const CALL_REPORT_CARDS: CallReportCard[] = [
  { label: "Total Calls Received", value: "4561", icon: EyePng, bg: "#F8FAFF", border: "#EEF3FF" },
  { label: "Total Calls Attempted", value: "3215", icon: MouseCircleGreenIcon, bg: "#F7FCF9", border: "#EAF7EE" },
  { label: "Connected", value: "234", icon: ProfileTwoUserIcon, bg: "#FFF9F9", border: "#FDEEEF" },
  { label: "Not Connected", value: "14.8%", icon: MouseCircleIcon, bg: "#F8FAFF", border: "#EEF3FF" },
  { label: "Avg. Call Duration", value: "5:42 min", icon: DollarCircleIcon, bg: "#FFFCF7", border: "#FDF3E4" },
];

export const CALL_REPORT_ROWS: CallReportRow[] = [
  { id: 1, name: "Michael Brown", dateTime: "17/05/2024 | 06:15 AM", phoneNumber: "+91 87650 23456", callDuration: "3:10 Min", callsReceivedBy: "Noah Carter", status: "Connected", mode: "attempted" },
  { id: 2, name: "Alex Johnson", dateTime: "29/02/2028 | 04:00 PM", phoneNumber: "+91 76540 34567", callDuration: "7:20 Min", callsReceivedBy: "Mason Reed", status: "Not-Connected", mode: "attempted" },
  { id: 3, name: "Michael Brown", dateTime: "25/12/2023 | 01:00 PM", phoneNumber: "+91 54320 56789", callDuration: "6:05 Min", callsReceivedBy: "Noah Carter", status: "Connected", mode: "attempted" },
  { id: 4, name: "John Smith", dateTime: "22/10/2023 | 05:05 PM", phoneNumber: "+91 10987 65432", callDuration: "2:15 Min", callsReceivedBy: "Henry Cavil", status: "Connected", mode: "received" },
  { id: 5, name: "Emily Carter", dateTime: "11/01/2025 | 08:30 AM", phoneNumber: "+91 09876 54321", callDuration: "4:45 Min", callsReceivedBy: "Ethan Parker", status: "Connected", mode: "received" },
  { id: 6, name: "Sophia Davis", dateTime: "03/09/2026 | 07:45 PM", phoneNumber: "+91 98760 12345", callDuration: "5:30 Min", callsReceivedBy: "Lucas Bennett", status: "Not-Connected", mode: "attempted" },
  { id: 7, name: "Alex Johnson", dateTime: "08/11/2025 | 02:30 PM", phoneNumber: "+91 65430 45678", callDuration: "1:50 Min", callsReceivedBy: "Oliver Grant", status: "Connected", mode: "received" },
  { id: 8, name: "Mia Scott", dateTime: "15/03/2025 | 11:20 AM", phoneNumber: "+91 76891 23411", callDuration: "3:45 Min", callsReceivedBy: "Mason Reed", status: "Connected", mode: "received" },
  { id: 9, name: "Liam Grey", dateTime: "20/06/2024 | 09:10 AM", phoneNumber: "+91 81234 98760", callDuration: "2:55 Min", callsReceivedBy: "Noah Carter", status: "Connected", mode: "attempted" },
  { id: 10, name: "Ava James", dateTime: "07/07/2024 | 12:40 PM", phoneNumber: "+91 93210 33221", callDuration: "8:05 Min", callsReceivedBy: "Henry Cavil", status: "Not-Connected", mode: "attempted" },
  { id: 11, name: "Noel White", dateTime: "13/08/2024 | 04:55 PM", phoneNumber: "+91 70012 55443", callDuration: "5:12 Min", callsReceivedBy: "Ethan Parker", status: "Connected", mode: "received" },
  { id: 12, name: "Emma Reed", dateTime: "21/09/2024 | 03:05 PM", phoneNumber: "+91 84567 12890", callDuration: "6:40 Min", callsReceivedBy: "Oliver Grant", status: "Connected", mode: "received" },
];

export const CALL_TRANSCRIPT_LINES: CallTranscriptLine[] = [
  { time: "0:01", speaker: "Mike", text: "Good morning! You've reached Bloom Fertility Center. This is Mike. How can I help you today?" },
  { time: "0:03", speaker: "John", text: "Hi Mike, I'm calling to get some information about IVF. My wife and I are considering starting treatment." },
  { time: "0:05", speaker: "Mike", text: "Of course, John. I'd be happy to guide you. May I know your wife's age and how long you both have been trying to conceive?" },
  { time: "0:09", speaker: "John", text: "She's 32, and we've been trying for about four years now." },
  { time: "0:15", speaker: "Mike", text: "Thank you. Have you undergone any treatments earlier, like IUI or IVF?" },
  { time: "0:20", speaker: "John", text: "We tried two IUIs this year, but they weren't successful. No IVF yet." },
  { time: "0:30", speaker: "Mike", text: "Understood. In that case, IVF is usually the recommended next step. Have any recent tests been done for your wife, like AMH or ultrasound?" },
  { time: "0:35", speaker: "John", text: "Yes, AMH was done last month — the value was 1.1." },
  { time: "0:45", speaker: "Mike", text: "Thank you, John. An AMH of 1.1 indicates slightly reduced ovarian reserve, but many patients with similar results still achieve successful IVF outcomes. Would you like me to help schedule a consultation with our IVF specialist?" },
  { time: "1:03", speaker: "John", text: "Yes, that would be great. Preferably sometime this week in the morning." },
];
