import type { Ticket } from "../../../types/Settings.types";

export const TICKETS_MOCK: Ticket[] = [
  // --- NEW (18 Entries) ---
  {
    ticketNo: "TN-654321",
    labName: "Health Innovations Lab",
    subject: "Inquiry about account access issues",
    createdDate: "14/11/2025",
    dueDate: "29/11/2025",
    requestedBy: "Dr. Emily Carter",
    department: "Andrology",
    priority: "Low",
    assignedTo: "John Grant",
    status: "New",
    timeline: [
      { type: "received", time: "14/11/2025 | 09:15 AM" },
      { type: "assigned", user: "John Grant", time: "14/11/2025 | 11:30 AM" },
    ],
  },
  {
    ticketNo: "TN-987654",
    labName: "Wellness Research Center",
    subject: "Request for software installation help",
    createdDate: "15/11/2025",
    dueDate: "30/11/2025",
    requestedBy: "Dr. Michael Thompson",
    department: "Andrology",
    priority: "Medium",
    assignedTo: "Merry Parker",
    status: "New",
    timeline: [
      { type: "received", time: "15/11/2025 | 10:00 AM" },
      { type: "assigned", user: "Merry Parker", time: "15/11/2025 | 01:45 PM" },
    ],
  },
  {
    ticketNo: "TN-456789",
    labName: "BioSolutions Lab",
    subject: "Feedback on recent software update",
    createdDate: "20/11/2025",
    dueDate: "05/12/2025",
    requestedBy: "Sarah Johnson",
    department: "Reception",
    priority: "High",
    assignedTo: "Nexa Carter",
    status: "New",
    timeline: [
      { type: "received", time: "20/11/2025 | 08:30 AM" },
      { type: "assigned", user: "Nexa Carter", time: "20/11/2025 | 09:15 AM" },
    ],
  },
  {
    ticketNo: "TN-321654",
    labName: "Advanced Diagnostics Lab",
    subject: "Question regarding billing discrepancies",
    createdDate: "01/12/2025",
    dueDate: "16/12/2025",
    requestedBy: "Dr. David Lee",
    department: "Andrology",
    priority: "High",
    assignedTo: "Emilia Clarke",
    status: "New",
    timeline: [
      { type: "received", time: "01/12/2025 | 02:10 PM" },
      { type: "assigned", user: "Emilia Clarke", time: "01/12/2025 | 03:50 PM" },
    ],
  },
  {
    ticketNo: "TN-789123",
    labName: "Nutritional Science Lab",
    subject: "Assistance needed for password reset",
    createdDate: "10/12/2025",
    dueDate: "25/12/2025",
    requestedBy: "Dr. Jessica Brown",
    department: "Andrology",
    priority: "Low",
    assignedTo: "Noah Carter",
    status: "New",
    timeline: [
      { type: "received", time: "10/12/2025 | 11:00 AM" },
      { type: "assigned", user: "Noah Carter", time: "10/12/2025 | 12:20 PM" },
    ],
  },
  {
    ticketNo: "TN-234567",
    labName: "Genetic Research Institute",
    subject: "Report a bug in the application",
    createdDate: "25/12/2025",
    dueDate: "09/01/2026",
    requestedBy: "Er. Daniel Wilson",
    department: "Embryology",
    priority: "Medium",
    assignedTo: "Lily Foster",
    status: "New",
    timeline: [
      { type: "received", time: "25/12/2025 | 04:00 PM" },
      { type: "assigned", user: "Lily Foster", time: "26/12/2025 | 09:30 AM" },
    ],
  },
  {
    ticketNo: "TN-876543",
    labName: "Clinical Trials Lab",
    subject: "Request for feature enhancement",
    createdDate: "05/01/2026",
    dueDate: "20/01/2026",
    requestedBy: "Laura Martinez",
    department: "Reception",
    priority: "Low",
    assignedTo: "Emma Bennett",
    status: "New",
    timeline: [
      { type: "received", time: "05/01/2026 | 09:15 AM" },
      { type: "assigned", user: "Emma Bennett", time: "05/01/2026 | 11:00 AM" },
    ],
  },
  {
    ticketNo: "TN-543216",
    labName: "Pharmaceutical Development Lab",
    subject: "Inquiry about subscription plans",
    createdDate: "08/01/2026",
    dueDate: "23/01/2026",
    requestedBy: "Dr. Kevin Garcia",
    department: "Andrology",
    priority: "Medium",
    assignedTo: "Ethan Parker",
    status: "New",
    timeline: [
      { type: "received", time: "08/01/2026 | 01:20 PM" },
      { type: "assigned", user: "Ethan Parker", time: "08/01/2026 | 02:45 PM" },
    ],
  },
  {
    ticketNo: "TN-112233",
    labName: "City Medical Hub",
    subject: "Database synchronization error",
    createdDate: "10/01/2026",
    dueDate: "25/01/2026",
    requestedBy: "Dr. Alice Reed",
    department: "Pathology",
    priority: "High",
    assignedTo: "John Grant",
    status: "New",
    timeline: [
      { type: "received", time: "10/01/2026 | 10:45 AM" },
      { type: "assigned", user: "John Grant", time: "10/01/2026 | 12:00 PM" },
    ],
  },
  {
    ticketNo: "TN-445566",
    labName: "Metro Health Lab",
    subject: "Update contact information",
    createdDate: "11/01/2026",
    dueDate: "26/01/2026",
    requestedBy: "Mark Stevens",
    department: "Reception",
    priority: "Low",
    assignedTo: "Merry Parker",
    status: "New",
    timeline: [
      { type: "received", time: "11/01/2026 | 03:30 PM" },
      { type: "assigned", user: "Merry Parker", time: "11/01/2026 | 05:10 PM" },
    ],
  },
  {
    ticketNo: "TN-778899",
    labName: "Precision Bio Lab",
    subject: "Report export failure",
    createdDate: "12/01/2026",
    dueDate: "27/01/2026",
    requestedBy: "Dr. Robert Smith",
    department: "Andrology",
    priority: "Medium",
    assignedTo: "Nexa Carter",
    status: "New",
    timeline: [
      { type: "received", time: "12/01/2026 | 09:00 AM" },
      { type: "assigned", user: "Nexa Carter", time: "12/01/2026 | 10:45 AM" },
    ],
  },
  {
    ticketNo: "TN-102030",
    labName: "Nova Diagnostics",
    subject: "Slow login performance",
    createdDate: "13/01/2026",
    dueDate: "28/01/2026",
    requestedBy: "Jane Watson",
    department: "Andrology",
    priority: "High",
    assignedTo: "Emilia Clarke",
    status: "New",
    timeline: [
      { type: "received", time: "13/01/2026 | 11:20 AM" },
      { type: "assigned", user: "Emilia Clarke", time: "13/01/2026 | 01:15 PM" },
    ],
  },
  {
    ticketNo: "TN-405060",
    labName: "Starlight Research",
    subject: "Broken UI elements on mobile",
    createdDate: "14/01/2026",
    dueDate: "29/01/2026",
    requestedBy: "Dr. Peter Quill",
    department: "Embryology",
    priority: "Medium",
    assignedTo: "Noah Carter",
    status: "New",
    timeline: [
      { type: "received", time: "14/01/2026 | 08:45 AM" },
      { type: "assigned", user: "Noah Carter", time: "14/01/2026 | 10:00 AM" },
    ],
  },
  {
    ticketNo: "TN-708090",
    labName: "Eco Science Lab",
    subject: "Printer driver installation",
    createdDate: "15/01/2026",
    dueDate: "30/01/2026",
    requestedBy: "Bruce Banner",
    department: "Reception",
    priority: "Low",
    assignedTo: "Lily Foster",
    status: "New",
    timeline: [
      { type: "received", time: "15/01/2026 | 02:30 PM" },
      { type: "assigned", user: "Lily Foster", time: "15/01/2026 | 04:00 PM" },
    ],
  },
  {
    ticketNo: "TN-991122",
    labName: "Frontier Biotech",
    subject: "Email notification delays",
    createdDate: "16/01/2026",
    dueDate: "31/01/2026",
    requestedBy: "Tony Stark",
    department: "Andrology",
    priority: "High",
    assignedTo: "Emma Bennett",
    status: "New",
    timeline: [
      { type: "received", time: "16/01/2026 | 10:10 AM" },
      { type: "assigned", user: "Emma Bennett", time: "16/01/2026 | 12:45 PM" },
    ],
  },
  {
    ticketNo: "TN-334455",
    labName: "Apex Clinical Lab",
    subject: "Add new user permissions",
    createdDate: "17/01/2026",
    dueDate: "01/02/2026",
    requestedBy: "Natasha Romanoff",
    department: "Reception",
    priority: "Medium",
    assignedTo: "Ethan Parker",
    status: "New",
    timeline: [
      { type: "received", time: "17/01/2026 | 09:00 AM" },
      { type: "assigned", user: "Ethan Parker", time: "17/01/2026 | 11:30 AM" },
    ],
  },
  {
    ticketNo: "TN-667788",
    labName: "Summit Research",
    subject: "Missing records in history",
    createdDate: "18/01/2026",
    dueDate: "02/02/2026",
    requestedBy: "Steve Rogers",
    department: "Andrology",
    priority: "High",
    assignedTo: "John Grant",
    status: "New",
    timeline: [
      { type: "received", time: "18/01/2026 | 01:20 PM" },
      { type: "assigned", user: "John Grant", time: "18/01/2026 | 03:00 PM" },
    ],
  },
  {
    ticketNo: "TN-009988",
    labName: "Legacy Health",
    subject: "Finalizing lab results",
    createdDate: "19/01/2026",
    dueDate: "03/02/2026",
    requestedBy: "Wanda Maximoff",
    department: "Pathology",
    priority: "Low",
    assignedTo: "Merry Parker",
    status: "New",
    timeline: [
      { type: "received", time: "19/01/2026 | 11:50 AM" },
      { type: "assigned", user: "Merry Parker", time: "19/01/2026 | 02:15 PM" },
    ],
  },

  // --- PENDING (5 Entries) ---
  {
    ticketNo: "TN-P10001",
    labName: "Blue Wave Lab",
    subject: "Awaiting insurance verification",
    createdDate: "20/01/2026",
    dueDate: "04/02/2026",
    requestedBy: "Dr. Strange",
    department: "Andrology",
    priority: "Medium",
    assignedTo: "Emilia Clarke",
    status: "Pending",
    timeline: [
      { type: "received", time: "20/01/2026 | 10:00 AM" },
      { type: "assigned", user: "Emilia Clarke", time: "20/01/2026 | 11:30 AM" },
    ],
  },
  {
    ticketNo: "TN-P10002",
    labName: "Crystal Clear Labs",
    subject: "Pending vendor hardware approval",
    createdDate: "21/01/2026",
    dueDate: "05/02/2026",
    requestedBy: "Scott Lang",
    department: "Reception",
    priority: "High",
    assignedTo: "Noah Carter",
    status: "Pending",
    timeline: [
      { type: "received", time: "21/01/2026 | 08:30 AM" },
      { type: "assigned", user: "Noah Carter", time: "21/01/2026 | 10:45 AM" },
    ],
  },
  {
    ticketNo: "TN-P10003",
    labName: "Desert Rose Med",
    subject: "Need patient consent form",
    createdDate: "22/01/2026",
    dueDate: "06/02/2026",
    requestedBy: "Hope Pym",
    department: "Embryology",
    priority: "Low",
    assignedTo: "Lily Foster",
    status: "Pending",
    timeline: [
      { type: "received", time: "22/01/2026 | 11:00 AM" },
      { type: "assigned", user: "Lily Foster", time: "22/01/2026 | 01:20 PM" },
    ],
  },
  {
    ticketNo: "TN-P10004",
    labName: "Evergreen Center",
    subject: "System migration on hold",
    createdDate: "23/01/2026",
    dueDate: "07/02/2026",
    requestedBy: "Carol Danvers",
    department: "Andrology",
    priority: "High",
    assignedTo: "Emma Bennett",
    status: "Pending",
    timeline: [
      { type: "received", time: "23/01/2026 | 09:15 AM" },
      { type: "assigned", user: "Emma Bennett", time: "23/01/2026 | 11:00 AM" },
    ],
  },
  {
    ticketNo: "TN-P10005",
    labName: "Frostbite Research",
    subject: "Awaiting manager sign-off",
    createdDate: "24/01/2026",
    dueDate: "08/02/2026",
    requestedBy: "Nick Fury",
    department: "Pathology",
    priority: "Medium",
    assignedTo: "Ethan Parker",
    status: "Pending",
    timeline: [
      { type: "received", time: "24/01/2026 | 02:30 PM" },
      { type: "assigned", user: "Ethan Parker", time: "24/01/2026 | 04:50 PM" },
    ],
  },

  // --- RESOLVED (3 Entries) ---
  {
    ticketNo: "TN-R20001",
    labName: "Galaxy Diagnostics",
    subject: "Fixed login redirect loop",
    createdDate: "05/01/2026",
    dueDate: "10/01/2026",
    requestedBy: "Peter Parker",
    department: "Andrology",
    priority: "High",
    assignedTo: "Nexa Carter",
    status: "Resolved",
    timeline: [
      { type: "received", time: "05/01/2026 | 09:00 AM" },
      { type: "assigned", user: "Nexa Carter", time: "05/01/2026 | 10:30 AM" },
      { type: "resolved", user: "Nexa Carter", time: "09/01/2026 | 06:10 PM" },
    ],
  },
  {
    ticketNo: "TN-R20002",
    labName: "Horizon Health",
    subject: "Table styling bug resolved",
    createdDate: "06/01/2026",
    dueDate: "11/01/2026",
    requestedBy: "Mary Jane",
    department: "Reception",
    priority: "Low",
    assignedTo: "John Grant",
    status: "Resolved",
    timeline: [
      { type: "received", time: "06/01/2026 | 11:45 AM" },
      { type: "assigned", user: "John Grant", time: "06/01/2026 | 01:20 PM" },
      { type: "resolved", user: "John Grant", time: "10/01/2026 | 04:30 PM" },
    ],
  },
  {
    ticketNo: "TN-R20003",
    labName: "Infinity Lab",
    subject: "Updated API endpoints",
    createdDate: "07/01/2026",
    dueDate: "12/01/2026",
    requestedBy: "Gwen Stacy",
    department: "Embryology",
    priority: "Medium",
    assignedTo: "Merry Parker",
    status: "Resolved",
    timeline: [
      { type: "received", time: "07/01/2026 | 08:30 AM" },
      { type: "assigned", user: "Merry Parker", time: "07/01/2026 | 10:00 AM" },
      { type: "resolved", user: "Merry Parker", time: "11/01/2026 | 05:45 PM" },
    ],
  },

  // --- CLOSED (9 Entries) ---
  {
    ticketNo: "TN-C30001",
    labName: "Jupiter Med",
    subject: "Annual system maintenance",
    createdDate: "01/12/2025",
    dueDate: "05/12/2025",
    requestedBy: "Arthur Curry",
    department: "Andrology",
    priority: "Low",
    assignedTo: "Emilia Clarke",
    status: "Closed",
    timeline: [
      { type: "received", time: "01/12/2025 | 08:30 AM" },
      { type: "assigned", user: "Emilia Clarke", time: "01/12/2025 | 10:00 AM" },
      { type: "closed", user: "Emilia Clarke", time: "05/12/2025 | 05:00 PM" },
    ],
  },
  {
    ticketNo: "TN-C30002",
    labName: "Krypton Labs",
    subject: "Old account deactivation",
    createdDate: "02/12/2025",
    dueDate: "06/12/2025",
    requestedBy: "Lois Lane",
    department: "Reception",
    priority: "Medium",
    assignedTo: "Noah Carter",
    status: "Closed",
    timeline: [
      { type: "received", time: "02/12/2025 | 09:15 AM" },
      { type: "assigned", user: "Noah Carter", time: "02/12/2025 | 11:30 AM" },
      { type: "closed", user: "Noah Carter", time: "06/12/2025 | 03:20 PM" },
    ],
  },
  {
    ticketNo: "TN-C30003",
    labName: "Lunar Research",
    subject: "Q4 security audit completed",
    createdDate: "03/12/2025",
    dueDate: "07/12/2025",
    requestedBy: "Diana Prince",
    department: "Embryology",
    priority: "High",
    assignedTo: "Lily Foster",
    status: "Closed",
    timeline: [
      { type: "received", time: "03/12/2025 | 10:40 AM" },
      { type: "assigned", user: "Lily Foster", time: "03/12/2025 | 01:00 PM" },
      { type: "closed", user: "Lily Foster", time: "07/12/2025 | 04:50 PM" },
    ],
  },
  {
    ticketNo: "TN-C30004",
    labName: "Mountain View Lab",
    subject: "Printer setup complete",
    createdDate: "04/12/2025",
    dueDate: "08/12/2025",
    requestedBy: "Barry Allen",
    department: "Andrology",
    priority: "Low",
    assignedTo: "Emma Bennett",
    status: "Closed",
    timeline: [
      { type: "received", time: "04/12/2025 | 11:00 AM" },
      { type: "assigned", user: "Emma Bennett", time: "04/12/2025 | 01:20 PM" },
      { type: "closed", user: "Emma Bennett", time: "08/12/2025 | 02:30 PM" },
    ],
  },
  {
    ticketNo: "TN-C30005",
    labName: "Nebula Diagnostics",
    subject: "Software training session",
    createdDate: "05/12/2025",
    dueDate: "09/12/2025",
    requestedBy: "Hal Jordan",
    department: "Reception",
    priority: "Medium",
    assignedTo: "Ethan Parker",
    status: "Closed",
    timeline: [
      { type: "received", time: "05/12/2025 | 08:30 AM" },
      { type: "assigned", user: "Ethan Parker", time: "05/12/2025 | 10:45 AM" },
      { type: "closed", user: "Ethan Parker", time: "09/12/2025 | 04:00 PM" },
    ],
  },
  {
    ticketNo: "TN-C30006",
    labName: "Oceanic Science",
    subject: "Billing cycle adjustment",
    createdDate: "06/12/2025",
    dueDate: "10/12/2025",
    requestedBy: "Victor Stone",
    department: "Andrology",
    priority: "High",
    assignedTo: "John Grant",
    status: "Closed",
    timeline: [
      { type: "received", time: "06/12/2025 | 02:15 PM" },
      { type: "assigned", user: "John Grant", time: "06/12/2025 | 04:00 PM" },
      { type: "closed", user: "John Grant", time: "10/12/2025 | 05:30 PM" },
    ],
  },
  {
    ticketNo: "TN-C30007",
    labName: "Polaris Health",
    subject: "Updated logo on reports",
    createdDate: "07/12/2025",
    dueDate: "11/12/2025",
    requestedBy: "Oliver Queen",
    department: "Pathology",
    priority: "Low",
    assignedTo: "Merry Parker",
    status: "Closed",
    timeline: [
      { type: "received", time: "07/12/2025 | 09:20 AM" },
      { type: "assigned", user: "Merry Parker", time: "07/12/2025 | 11:00 AM" },
      { type: "closed", user: "Merry Parker", time: "11/12/2025 | 03:15 PM" },
    ],
  },
  {
    ticketNo: "TN-C30008",
    labName: "Quasar Lab",
    subject: "Email server migration",
    createdDate: "08/12/2025",
    dueDate: "12/12/2025",
    requestedBy: "Dinah Lance",
    department: "Andrology",
    priority: "Medium",
    assignedTo: "Nexa Carter",
    status: "Closed",
    timeline: [
      { type: "received", time: "08/12/2025 | 10:10 AM" },
      { type: "assigned", user: "Nexa Carter", time: "08/12/2025 | 12:45 PM" },
      { type: "closed", user: "Nexa Carter", time: "12/12/2025 | 06:00 PM" },
    ],
  },
  {
    ticketNo: "TN-C30009",
    labName: "Radiant Med",
    subject: "New user onboarding",
    createdDate: "09/12/2025",
    dueDate: "13/12/2025",
    requestedBy: "John Diggle",
    department: "Reception",
    priority: "High",
    assignedTo: "Emilia Clarke",
    status: "Closed",
    timeline: [
      { type: "received", time: "09/12/2025 | 08:45 AM" },
      { type: "assigned", user: "Emilia Clarke", time: "09/12/2025 | 10:30 AM" },
      { type: "closed", user: "Emilia Clarke", time: "13/12/2025 | 02:20 PM" },
    ],
  },
];