// ====================== Task Type Config ======================
export const TASK_TYPES = [
  "Follow Up",
  "Call Patient",
  "Book Appointment",
  "Send Message",
  "Send Email",
  "Review Details",
  "No Action",
] as const;

export type TaskType = (typeof TASK_TYPES)[number];

// ====================== Action Status Options ======================
export const ACTION_STATUS_OPTIONS = [
  { label: "To-do",       value: "to_do"       },
  { label: "In Progress", value: "in_progress" },
  { label: "Completed",   value: "completed"   },
] as const;

export type ActionStatusValue = "to_do" | "in_progress" | "completed";

// ====================== Source Options ======================
export const SOURCE_OPTIONS = ["Direct", "Referral", "Social Media", "Other"] as const;

// "Referral" sub-sources are fetched dynamically from the backend referral departments API
export const SUB_SOURCE_OPTIONS: Record<string, string[]> = {
  "Social Media": ["Facebook", "Instagram", "LinkedIn", "Google Ads"],
  Direct: ["Walk-in", "Conference","Phone Call", "Website", "Google", "Gmail"],
};

// ====================== Referral Department Options ======================
export const REFERRAL_DEPARTMENT_OPTIONS = [
  "Doctors",
  "Corporate HR",
  "Insurance Partner",
  "Direct Walk-in",
  "Online / Digital",
  "NGO / Trust",
  "Government Body",
  "Other",
] as const;

export type ReferralDepartmentOption = (typeof REFERRAL_DEPARTMENT_OPTIONS)[number];

// ====================== Default Next Action Status Options ======================
export const DEFAULT_NEXT_ACTION_STATUS_OPTIONS = [
  { label: "New", value: "new" },
  { label: "Follow-up", value: "follow_up" },
  { label: "Converted", value: "converted" },
  { label: "Lost", value: "lost" },
] as const;

export type NextActionStatusOption = { label: string; value: string };

// ====================== Lead Generated By Object ======================
export type LeadGeneratedByObject = {
  id?: number | null;
  first_name: string;
  last_name: string;
  role: string;
  email: string;
};

// ====================== Referral Source Object ======================
// Sent as a separate JSON object to the backend (not inside LeadPayload)
// Backend uses: first_name, last_name, email, role to create ReferralSource
export type ReferralSourceObject = {
  first_name: string;
  last_name: string;
  email: string;
  role: string;
};

// ====================== Payload Type ======================
export type LeadPayload = {
  clinic_id: number;
  department_id: number;
  stage_id?: string | number | null;
  campaign_id: string | null;
  assigned_to_id: number | null;
  assigned_to_name?: string | null;
  // personal_id + personal_name = appointment personnel (medical) or lead generated by user id (contracts)
  personal_id: number | null;
  personal_name?: string | null;
  // lead_generated_by removed — backend Lead model has no such field
  // contracts app sends selectedLeadGeneratedBy as referral_source object separately
  full_name: string;
  contact_no: string;
  age: number | null;
  gender?: "male" | "female" | null;
  marital_status: "single" | "married" | null;
  email: string | null;
  language_preference: string;
  location: string;
  address: string;
  partner_inquiry: boolean;
  partner_full_name: string;
  partner_age: number | null;
  partner_gender: "male" | "female" | null;
  source: string;
  sub_source?: string;
  next_action_status?: string | null;
  next_action_description?: string;
  next_action_type?: string;
  action_status?: ActionStatusValue | null;    // ← NEW
  lead_status?:
    | "new"
    | "contacted"
    | "appointment"
    | "follow up"
    | "negotiation"
    | "proposal sent"
    | "contract signed"
    | "converted"
    | "cycle_conversion"
    | "lost"
    | "lost lead";
  treatment_interest: string;
  book_appointment: boolean;
  appointment_date: string | null;
  slot: string;
  remark: string;
  is_active: boolean;
  referral_department_id?: number | null;

  // ── Contact Information (contracts app) ───────────────────────────────────
  contact_full_name?: string | null;
  contact_designation?: string | null;
  contact_phone?: string | null;
  contact_email?: string | null;
};

// ====================== Campaign Type ======================
export type CampaignData = {
  id: string;
  campaign_name?: string;
  campaign_mode?: number;
  social_media?: Array<{ platform_name?: string }>;
  is_active?: boolean;
};

// ====================== API Error Type ======================
export type ApiError = {
  response?: {
    status?: number;
    data?: {
      detail?: string;
      message?: string;
      error?: string;
      request_id?: string;
      [key: string]: unknown;
    };
  };
  message?: string;
};

// ====================== Document Config ======================
export const ALLOWED_DOC_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
];

export const MAX_DOC_SIZE_MB = 10;

export const getDocColor = (name: string): string => {
  const ext = name.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    pdf: "#EF4444",
    doc: "#3B82F6",
    docx: "#3B82F6",
    jpg: "#10B981",
    jpeg: "#10B981",
    png: "#10B981",
    webp: "#10B981",
  };
  return map[ext] ?? "#6366F1";
};

// ====================== Value Helpers ======================
export const strOrNull = (val: string | undefined | null): string | null =>
  val && val.trim() !== "" ? val.trim() : null;

export const intOrNull = (val: string | undefined | null): number | null => {
  const n = Number(val);
  return val && val.trim() !== "" && !isNaN(n) ? n : null;
};

export const intOrFallback = (
  val: string | undefined | null,
  fallback: number,
): number => {
  const n = Number(val);
  return val && val.trim() !== "" && !isNaN(n) && n > 0 ? n : fallback;
};

// ====================== Time Slots ======================
export const TIME_SLOTS = [
  "09:00 AM - 09:30 AM",
  "09:30 AM - 10:00 AM",
  "10:00 AM - 10:30 AM",
  "10:30 AM - 11:00 AM",
  "11:00 AM - 11:30 AM",
  "11:30 AM - 12:00 PM",
  "12:00 PM - 12:30 PM",
  "12:30 PM - 01:00 PM",
  "02:00 PM - 02:30 PM",
  "02:30 PM - 03:00 PM",
  "03:00 PM - 03:30 PM",
  "03:30 PM - 04:00 PM",
  "04:00 PM - 04:30 PM",
  "04:30 PM - 05:00 PM",
  "05:00 PM - 05:30 PM",
  "05:30 PM - 06:00 PM",
];

// ====================== MUI Styles ======================
export const inputStyle = {
  "& .MuiOutlinedInput-root": {
    borderRadius: "8px",
    fontSize: "0.875rem",
    "& fieldset": { borderColor: "#E2E8F0" },
    "&:hover fieldset": { borderColor: "#CBD5E1" },
    "&.Mui-focused fieldset": { borderColor: "#6366F1" },
  },
};

export const readOnlyStyle = {
  "& .MuiOutlinedInput-root": {
    borderRadius: "8px",
    fontSize: "0.875rem",
    bgcolor: "#F1F5F9",
    "& fieldset": { borderColor: "#E2E8F0" },
    "&:hover fieldset": { borderColor: "#E2E8F0" },
    "&.Mui-focused fieldset": { borderColor: "#E2E8F0" },
  },
};

export const labelStyle = {
  fontSize: "0.75rem",
  fontWeight: 600,
  color: "#64748B",
  mb: 0.5,
  display: "block",
};