export type AppType = "medical" | "contracts";

export type LeadStatusOption =
  | "New"
  | "Appointment"
  | "Follow Up"
  | "Negotiation"
  | "Proposal Sent"
  | "Contract Signed"
  | "Converted Lead"
  | "Lost Lead";

// Keep as AppType (widened), so comparisons below don't throw TS2367.
export const APP_TYPE = "contracts" as AppType; // change to "medical" when needed

const CURRENT_APP_TYPE: AppType = APP_TYPE;

export const IS_MEDICAL_APP = CURRENT_APP_TYPE === "medical";
export const IS_CONTRACTS_APP = CURRENT_APP_TYPE === "contracts";

// ── Tab / section copy ────────────────────────────────────────────────────────
export const FLOW_COPY_BY_APP = {
  medical: {
    infoTab: "Patient Info",

    // New keys
    detailsStep: "Patient Details",
    medicalStep: "Medical Details",

    // Backward-compatible keys (if older files still use step1/step2/step3)
    step1: "Patient Details",
    step2: "Medical Details",
    step3: "Book Appointment",

    medicalSection: "Medical Details",
    treatmentLabel: "Medical Interest",
    treatmentOptions: [
      "IVF",
      "IUI",
      "ICSI",
      "Donor Egg",
      "Surrogacy",
      "Fertility Preservation",
      "Male Infertility",
      "Other",
    ],
    contactSectionLabel: "Contact Information",
    showGenderAgeDob: true, // show Gender, Age, Marital Status in Lead Info
    showDesignation: false, // Contact Info: Designation field
    showLeadGeneratedBy: false, // Assignee section: Lead Generated By
    showDepartment: true, // Appointment stepper: Department field
  },
  contracts: {
    infoTab: "Lead Info",

    // New keys
    detailsStep: "Lead Details",
    medicalStep: "Product Details",

    // Backward-compatible keys
    step1: "Lead Details",
    step2: "Product Details",
    step3: "Book Appointment",

    medicalSection: "Product Information",
    treatmentLabel: "Product Interest",
    treatmentOptions: ["PGT-M", "PGT-A", "PGT-SR"],
    contactSectionLabel: "Contact Information",
    showGenderAgeDob: false,
    showDesignation: true,
    showLeadGeneratedBy: true,
    showDepartment: false,
  },
} as const;

// ── Status options per app ────────────────────────────────────────────────────
export const STATUS_OPTIONS_BY_APP = {
  medical: [
    "New",
    "Appointment",
    "Follow Up",
    "Converted Lead",
    "Lost Lead",
  ],
  contracts: [
    "New",
    "Follow Up",
    "Negotiation",
    "Proposal Sent",
    "Contract Signed",
    "Converted Lead",
    "Lost Lead",
  ],
} as const;

export const ACTIVE_FLOW_COPY = FLOW_COPY_BY_APP[APP_TYPE];
export const ACTIVE_STATUS_OPTIONS = STATUS_OPTIONS_BY_APP[APP_TYPE];