name: LMS-Clinic Frontend Push Trigger

on:
  push:
    branches:
      - devops-build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # ================= CHECKOUT CODE =================
      - name: Checkout repository
        uses: actions/checkout@v4

      # ================= DOCKER BUILDX =================
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ================= DOCKER LOGIN =================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ================= BUILD IMAGE =================
      - name: Build Docker image
        run: |
          docker build --no-cache \
          --build-arg VITE_API_BASE_URL=https://lms-vidaisolutions.metavaratechnologies.com/api \
          -f devops/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/clinic-frontend:latest .

      # ================= PUSH IMAGE =================
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/clinic-frontend:latest

      # ================= DEPLOY TO VPS =================
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

          script: |

            echo "Pull latest clinic frontend image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/clinic-frontend:latest

            echo "Stop old clinic frontend container"
            docker stop clinic-frontend || true

            echo "Remove old clinic frontend container"
            docker rm clinic-frontend || true

            echo "Start new clinic frontend container"

            docker run -d \
              --restart always \
              --name clinic-frontend \
              -p 3004:80 \
              ${{ secrets.DOCKER_USERNAME }}/clinic-frontend:latest

            echo "Clinic frontend deployed successfully"

            echo "Running containers:"
            docker ps
